name: Validate renovate config

on:
  push:
    branches: [master]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: "16.9.1"
      - name: Validate renovate config
        run: |
          for file in *.json
          do
            echo "[CI] Let's validate $file"
            cp $file renovate.json
            npx --package renovate -c 'renovate-config-validator'
            rm renovate.json
          done
